version: "3"

services:
  nimiq-miner:
    image: jpsecher/nimiq-miner
    command: --wallet-address=NQ6272GHCS6H3XL5L09SFGAM34MK7CU11JFE --type=light --pool=pool.nimiq.watch:8443
    volumes:
      - nimiq-miner:/home/nimiq
    restart: on-failure

volumes:
  nimiq-miner:
