version: "3.5"

services:
  nimiq-miner:
    image: jpsecher/nimiq-miner
    command: --wallet-address=NQ6272GHCS6H3XL5L09SFGAM34MK7CU11JFE --type=light --pool=pool.acemining.co:8443
    volumes:
      - nimiq-miner:/home/nimiq
    deploy:
      resources:
        limits:
          cpus: '1.0'
      restart_policy:
        condition: on-failure
volumes:
  nimiq-miner:
