version: "2.4"

services:
  nimiq-miner:
    image: jpsecher/nimiq-miner
    cpus: 20
    command: --wallet-address=NQ97FM05GUG8LV8C2FNC4TEML176LVHNR02L --type=light --pool=pool.acemining.co:8443
    volumes:
      - nimiq-miner:/home/nimiq
    restart: on-failure

volumes:
  nimiq-miner:
